src/UA/MatchBundle/Entity/Match/matchs.php
<?php

namespace UA\MatchBundle\Entity\Match;

use Doctrine\ORM\Mapping as ORM;

/**
 * matchs
 *
 * @ORM\Table(name="_matchs")
 * @ORM\Entity(repositoryClass="UA\MatchBundle\Entity\Match\matchsRepository")
 */
class matchs
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="UA\MatchBundle\Entity\Match\team")
     * @ORM\JoinColumn(nullable=false)
     */
    private $teamA;

    /**
     * @ORM\ManyToOne(targetEntity="UA\MatchBundle\Entity\Match\team")
     * @ORM\JoinColumn(nullable=true)
     */
    private $teamB;

    /**
     * @var integer
     *
     * @ORM\Column(name="scoreA", type="smallint", nullable=true)
     */
    private $scoreA;

    /**
     * @var integer
     *
     * @ORM\Column(name="scoreB", type="smallint", nullable=true)
     */
    private $scoreB;

    /**
     * @var string
     *
     * @ORM\Column(name="step", type="string", length=255)
     */
    private $step;

    /**
     * @ORM\ManyToOne(targetEntity="UA\MatchBundle\Entity\game", inversedBy="matchs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $game;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="horaire", type="datetime", nullable=true)
     */
    private $horaire;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    public function getPool() {
        return $this->teamA->getPool();
    }


    /**
     * Set scoreA
     *
     * @param integer $scoreA
     * @return matchs
     */
    public function setScoreA($scoreA)
    {
        $this->scoreA = $scoreA;
    
        return $this;
    }

    /**
     * Get scoreA
     *
     * @return integer 
     */
    public function getScoreA()
    {
        return $this->scoreA;
    }

    /**
     * Set scoreB
     *
     * @param integer $scoreB
     * @return matchs
     */
    public function setScoreB($scoreB)
    {
        $this->scoreB = $scoreB;
    
        return $this;
    }

    /**
     * Get scoreB
     *
     * @return integer 
     */
    public function getScoreB()
    {
        return $this->scoreB;
    }

    /**
     * Set step
     *
     * @param string $step
     * @return matchs
     */
    public function setStep($step)
    {
        $this->step = $step;
    
        return $this;
    }

    /**
     * Get step
     *
     * @return string 
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     * Set horaire
     *
     * @param \DateTime $horaire
     * @return matchs
     */
    public function setHoraire($horaire)
    {
        $this->horaire = $horaire;
    
        return $this;
    }

    /**
     * Get horaire
     *
     * @return \DateTime 
     */
    public function getHoraire()
    {
        return $this->horaire;
    }

    /**
     * Set teamA
     *
     * @param \UA\MatchBundle\Entity\Match\team $teamA
     * @return matchs
     */
    public function setTeamA(\UA\MatchBundle\Entity\Match\team $teamA)
    {
        $this->teamA = $teamA;
    
        return $this;
    }

    /**
     * Get teamA
     *
     * @return \UA\MatchBundle\Entity\Match\team 
     */
    public function getTeamA()
    {
        return $this->teamA;
    }

    /**
     * Set teamB
     *
     * @param \UA\MatchBundle\Entity\Match\team $teamB
     * @return matchs
     */
    public function setTeamB(\UA\MatchBundle\Entity\Match\team $teamB)
    {
        $this->teamB = $teamB;
    
        return $this;
    }

    /**
     * Get teamB
     *
     * @return \UA\MatchBundle\Entity\Match\team 
     */
    public function getTeamB()
    {
        return $this->teamB;
    }

    /**
     * Set game
     *
     * @param \UA\MatchBundle\Entity\game $game
     * @return matchs
     */
    public function setGame(\UA\MatchBundle\Entity\game $game)
    {
        $this->game = $game;
    
        return $this;
    }

    /**
     * Get game
     *
     * @return \UA\MatchBundle\Entity\game 
     */
    public function getGame()
    {
        return $this->game;
    }
}

src/UA/MatchBundle/Resources/views/MatchView/gameSelection.html.twig
{% extends "UAMatchBundle::layout.html.twig" %}
{% set menuActive = 'matchs' %}

{% block title %}{{ parent() }} - Sélection du jeux{% endblock %}
{% block headerTitle %}<h3>{{'header.matchs'|trans}} <small>{{ 'match.selectionTitle'|trans }}</small></h3>{% endblock %}

{% block body %}
	<div id="GamesGestion">
		{% for game in games %}
			<p class="game">
				<img src="{{ asset('uploads/img/' ~ game.pictures) }}" alt="{{game.pictures}}"><br />
				<span class="gameName">{{game.name}}</span>
				<span class="controlGame">
					<a href="{{ path('UAMatchBundle_ViewMatchforGame', {'id' : game.id}) }}" class="valide">
						<span class="glyphicon glyphicon-eye-open"></span>
					</a>
				</span>
			</p>
		{% endfor %}
	</div>
	{{ parent() }}
{% endblock %}

src/UA/MatchBundle/Resources/views/MatchView/viewMatchs.html.twig
{% extends "UAMatchBundle::layout.html.twig" %}
{% set menuActive = 'matchs' %}

{% block title %}{{ parent() }} - {{'match.title'|trans}}{% endblock %}
{% block headerTitle %}<h3>{{'header.matchs'|trans}} <small>{{'match.title'|trans}}</small></h3>{% endblock %}

{% block body %}
	{% set poolBefore = 0 %}
	{% set stepBefore = 0 %}
	{% for match in Matchs if Matchs %}
		<!--Close-->
		{% if match.pool != poolBefore %}
			{% if match.pool != 1 %}
			</table>
			</div>
			{% endif %}

			<div class="panel panel-default pull-left" style="margin-left: 5px;">
				<div class="panel-heading">Pool {{ match.pool }}</div>
					<table class="table">

			{% set poolBefore = match.pool %}
		{% endif %}
			
		<tr>
			<td>{{ match.TeamA.name}}</td>
			<td>{{ match.scoreA }}</td>
			<td>{{ match.scoreB }}</td>
			<td class="text-right">{{ match.TeamB.name }}</td>
			<td class="text-right">
				{% if is_granted('ROLE_ARBITRE') %}
					<a href="{{ path('UAMatchBundle_hour', {'MatchID' : match.id}) }}" class="btn btn-xs btn-default btn-hour">
						<span class="glyphicon glyphicon-time"></span>
					</a>
					<a href="{{ path('UAMatchBundle_Arbitrage', {'MatchID' : match.id}) }}" class="btn btn-xs btn-default btn-modif" data-original-title="{{'tooltip.score'|trans}}">
						<span class="glyphicon glyphicon-check"></span>
					</a>
				{% endif %}
			</td>
		</tr>
		{% if match.horaire and match.horaire > date() %}
			<tr>
				{% set nbrDay = match.horaire|date('d') - date()|date('d') %}
				<td colspan="5">{{ 'match.hour'|transchoice(nbrDay, {'%h%': match.horaire|date('H:i')}) }}</td>
			</tr>	
		{% endif %}

		<!--Close last panel-->
		{% if loop.index == Matchs|length %}
			</table>
		</div>
		{% endif %}
	{% else %}
		<div class="alert alert-danger">{{ 'error.MatchNotExisting'|trans }}</div>
		<a href="{{ path('UAMatchBundle_ViewGameSelect') }}" class="btn btn-default">
			<span class="glyphicon glyphicon-chevron-left"></span>
			{{ 'match.MatchReturn'|trans }}
		</a>
	{% endfor %}
	{% for match in Tree %}
		<!--Close-->
		{% if match.step|split(';')[0] != stepBefore %}
			
			</table>
			</div>

			<div class="panel panel-default pull-left" style="margin-left: 5px;">
				<div class="panel-heading">{{ match.step|split(';')[0] }}e</div>
					<table class="table">

			{% set stepBefore = match.step|split(';')[0] %}
		{% endif %}
			
		<tr>
			<td>{{ match.TeamA.name}}</td>
			<td>{{ match.scoreA }}</td>
			<td>{{ match.scoreB }}</td>
			<td class="text-right">{{ match.TeamB.name }}</td>
			<td class="text-right">
				{% if is_granted('ROLE_ARBITRE') %}
					<a href="{{ path('UAMatchBundle_hour', {'MatchID' : match.id}) }}" class="btn btn-xs btn-default btn-hour">
						<span class="glyphicon glyphicon-time"></span>
					</a>
					<a href="{{ path('UAMatchBundle_Arbitrage', {'MatchID' : match.id}) }}" class="btn btn-xs btn-default btn-modif" data-original-title="{{'tooltip.score'|trans}}">
						<span class="glyphicon glyphicon-check"></span>
					</a>
				{% endif %}
			</td>
		</tr>
		{% if match.horaire %}
			<tr>
				{% set nbrDay = match.horaire|date('d') - date()|date('d') %}
				<td colspan="5">{{ 'match.hour'|transchoice(nbrDay, {'%h%': match.horaire|date('H:i')}) }}</td>
			</tr>	
		{% endif %}

		<!--Close last panel-->
		{% if loop.index == Tree|length %}
			</table>
		</div>
		{% endif %}
	{% endfor %}
	<div class="clearfix"></div>
	{{ parent() }}
{% endblock %}

{% block javascripts %}
	{{parent()}}
	{% javascripts 
				'js/tooltip.js'
				'js/referee.js' %}
		<script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
{% endblock %}